version: '3.1'

services: 
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schooldb
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data

  schoolserver:
    build: ./schoolserver
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always

  schoolweb:
    build: ./schoolweb-osn
    ports:
      - 3000:3000
    depends_on:
      - db
      - schoolserver
    restart: always

volumes:
  db:
